# -*- coding: utf-8 -*-
"""3dvizualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Dan1k753/fb00ce1c2725a710dffa24e4bba8d417/3dvizualization.ipynb
"""

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go


pio.renderers.default = "colab"

df = pd.read_csv('clean_data.csv')
fig = go.Figure(data=[go.Scatter3d(
    x=df['E'],
    y=df['N'],
    z=df['U'],
    mode='lines',
    line=dict(
        width=6,
        color=df['speed'],
        colorscale='Viridis',
        showscale=True
    )
)])
fig.update_layout(

    paper_bgcolor='black',
    font_color='#00FF00',

    scene=dict(

        bgcolor='black',


        xaxis=dict(
            gridcolor='#003300',
            zerolinecolor='#00FF00',
            backgroundcolor='black',
            showbackground=True
        ),
        yaxis=dict(
            gridcolor='#003300',
            zerolinecolor='#00FF00',
            backgroundcolor='black',
            showbackground=True
        ),
        zaxis=dict(
            gridcolor='#003300',
            zerolinecolor='#00FF00',
            backgroundcolor='black',
            showbackground=True
        ),
        aspectmode='manual',
        aspectratio=dict(x=1, y=1, z=0.5)
    )
)

fig.update_scenes(
    xaxis_showgrid=True,
    yaxis_showgrid=True,
    zaxis_showgrid=True,
    xaxis_zeroline=True,
    yaxis_zeroline=True
)
fig.update_traces(line=dict(colorscale=['#003300', '#00FF00']))
fig.show()
